name: test-rust-app

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  execute:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Tests
        run: cargo test --verbose
